/*
THE MARKETING TEAM NEEDS TO DO RESEARCH ON THE MOST COMMON
NAMES OF THEIR CUSTOMERS AND NEEDS THE FIRST AND LAST NAME 
OF ALL CUSTOMERS WHO ARE REGISTERED IN THE SYSTEM.
*/

SELECT FirstName , LastName
FROM person.Person;